pipeline:

  pull-docker-image:
    image: docker
    commands:
      - docker pull nextcloud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push

  create-volume:
    image: docker
    commands:
      - docker volume create nextcloud-storage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push

  deploy-container:
    image: docker
    commands:
      - docker stop nextcloud || true
      - docker rm nextcloud || true
      - docker run -tid --name nextcloud -v nextcloud:/var/www/html -p 8084:80 nextcloud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
