pipeline:

  pull-docker-image:
    pull: true
    image: docker
    commands:
      - docker pull nextcloud:15.0.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push

  deploy-container:
    image: docker
    commands:
      - docker stop nextcloud || true
      - docker rm nextcloud || true
      - docker run -tid --name nextcloud -v /mnt/6tb/docker/opt/nextcloud:/var/www/html -p 8084:80 nextcloud:15.0.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
